/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */
export enum TYPES {
	SUBMIT_APP = 'SUBMIT_APP',
	SUBMIT_APP_BUILD = 'SUBMIT_APP_BUILD',
	SUBMIT_APP_LICENSING = 'SUBMIT_APP_LICENSING',
	SUBMIT_APP_PROFILE = 'SUBMIT_APP_PROFILE',
	UPDATE_APP_BUILD = 'UPDATE_APP_BUILD',
	UPDATE_APP_CATEGORIES = 'UPDATE_APP_CATEGORIES',
	UPDATE_APP_DESCRIPTION = 'UPDATE_APP_DESCRIPTION',
	UPDATE_APP_DOCUMENTATION_URL = 'UPDATE_APP_DOCUMENTATION_URL',
	UPDATE_APP_INSTALLATION_AND_UNINSTALLATION_GUIDE_URL = 'UPDATE_APP_INSTALLATION_AND_UNINSTALLATION_GUIDE_URL',
	UPDATE_APP_LICENSE = 'UPDATE_APP_LICENSE',
	UPDATE_APP_LICENSE_PRICE = 'UPDATE_APP_LICENSE_PRICE',
	UPDATE_APP_LOGO = 'UPDATE_APP_LOGO',
	UPDATE_APP_LXC_COMPATIBILITY = 'UPDATE_APP_LXC_COMPATIBILITY',
	UPDATE_APP_NAME = 'UPDATE_APP_NAME',
	UPDATE_APP_NOTES = 'UPDATE_APP_NOTES',
	UPDATE_APP_PRICE_MODEL = 'UPDATE_APP_PRICE_MODEL',
	UPDATE_APP_PUBLISHER_WEBSITE_URL = 'UPDATE_APP_PUBLISHER_WEBSITE_URL',
	UPLOAD_APP_STOREFRONT_IMAGES = 'UPLOAD_APP_STOREFRONT_IMAGES',
	UPDATE_APP_SUPPORT_URL = 'UPDATE_APP_SUPPORT_URL',
	UPDATE_APP_TAGS = 'UPDATE_APP_TAGS',
	UPDATE_APP_TRIAL_INFO = 'UPDATE_APP_TRIAL_INFO',
	UPDATE_APP_USAGE_TERMS_URL = 'UPDATE_APP_USAGE_TERMS_URL',
	UPDATE_APP_VERSION = 'UPDATE_APP_VERSION',
	UPDATE_CATALOG_ID = 'UPDATE_CATALOG_ID',
	UPDATE_OPTION_ID = 'UPDATE_OPTION_ID',
	UPDATE_PRODUCT_OPTION_ID = 'UPDATE_PRODUCT_OPTION_ID',
	UPDATE_PRODUCT_OPTION_VALUES_ID = 'UPDATE_PRODUCT_OPTION_VALUES_ID',
	UPDATE_SKU_TRIAL_ID = 'UPDATE_SKU_TRIAL_ID',
	UPDATE_SKU_VERSION_ID = 'UPDATE_SKU_VERSION_ID',
	UPLOAD_BUILD_ZIP_FILES = 'UPLOAD_BUILD_ZIP_FILES',
}
