/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.faro.model.FaroChannel;
import com.liferay.osb.faro.model.FaroChannelModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FaroChannel service. Represents a row in the &quot;OSBFaro_FaroChannel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FaroChannelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaroChannelImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroChannelImpl
 * @generated
 */
public class FaroChannelModelImpl
	extends BaseModelImpl<FaroChannel> implements FaroChannelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faro channel model instance should use the <code>FaroChannel</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBFaro_FaroChannel";

	public static final Object[][] TABLE_COLUMNS = {
		{"faroChannelId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createTime", Types.BIGINT}, {"modifiedTime", Types.BIGINT},
		{"channelId", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"permissionType", Types.INTEGER}, {"workspaceGroupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("faroChannelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("permissionType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("workspaceGroupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBFaro_FaroChannel (faroChannelId LONG not null primary key,groupId LONG,userId LONG,userName VARCHAR(75) null,createTime LONG,modifiedTime LONG,channelId VARCHAR(75) null,name VARCHAR(75) null,permissionType INTEGER,workspaceGroupId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBFaro_FaroChannel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY faroChannel.faroChannelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBFaro_FaroChannel.faroChannelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.faro.model.FaroChannel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.faro.model.FaroChannel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.faro.model.FaroChannel"),
		true);

	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long USERID_COLUMN_BITMASK = 4L;

	public static final long WORKSPACEGROUPID_COLUMN_BITMASK = 8L;

	public static final long FAROCHANNELID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.faro.model.FaroChannel"));

	public FaroChannelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _faroChannelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFaroChannelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _faroChannelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FaroChannel.class;
	}

	@Override
	public String getModelClassName() {
		return FaroChannel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FaroChannel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FaroChannel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroChannel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FaroChannel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FaroChannel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FaroChannel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FaroChannel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FaroChannel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FaroChannel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FaroChannel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FaroChannel.class.getClassLoader(), FaroChannel.class,
			ModelWrapper.class);

		try {
			Constructor<FaroChannel> constructor =
				(Constructor<FaroChannel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FaroChannel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FaroChannel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FaroChannel, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FaroChannel, Object>>();
		Map<String, BiConsumer<FaroChannel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FaroChannel, ?>>();

		attributeGetterFunctions.put(
			"faroChannelId",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getFaroChannelId();
				}

			});
		attributeSetterBiConsumers.put(
			"faroChannelId",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object faroChannelIdObject) {

					faroChannel.setFaroChannelId((Long)faroChannelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object groupIdObject) {

					faroChannel.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object userIdObject) {

					faroChannel.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object userNameObject) {

					faroChannel.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createTime",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getCreateTime();
				}

			});
		attributeSetterBiConsumers.put(
			"createTime",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object createTimeObject) {

					faroChannel.setCreateTime((Long)createTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedTime",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getModifiedTime();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedTime",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object modifiedTimeObject) {

					faroChannel.setModifiedTime((Long)modifiedTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"channelId",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getChannelId();
				}

			});
		attributeSetterBiConsumers.put(
			"channelId",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object channelIdObject) {

					faroChannel.setChannelId((String)channelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(FaroChannel faroChannel, Object nameObject) {
					faroChannel.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"permissionType",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getPermissionType();
				}

			});
		attributeSetterBiConsumers.put(
			"permissionType",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object permissionTypeObject) {

					faroChannel.setPermissionType(
						(Integer)permissionTypeObject);
				}

			});
		attributeGetterFunctions.put(
			"workspaceGroupId",
			new Function<FaroChannel, Object>() {

				@Override
				public Object apply(FaroChannel faroChannel) {
					return faroChannel.getWorkspaceGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"workspaceGroupId",
			new BiConsumer<FaroChannel, Object>() {

				@Override
				public void accept(
					FaroChannel faroChannel, Object workspaceGroupIdObject) {

					faroChannel.setWorkspaceGroupId(
						(Long)workspaceGroupIdObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getFaroChannelId() {
		return _faroChannelId;
	}

	@Override
	public void setFaroChannelId(long faroChannelId) {
		_faroChannelId = faroChannelId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_createTime = createTime;
	}

	@Override
	public long getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(long modifiedTime) {
		_modifiedTime = modifiedTime;
	}

	@Override
	public String getChannelId() {
		if (_channelId == null) {
			return "";
		}
		else {
			return _channelId;
		}
	}

	@Override
	public void setChannelId(String channelId) {
		_columnBitmask |= CHANNELID_COLUMN_BITMASK;

		if (_originalChannelId == null) {
			_originalChannelId = _channelId;
		}

		_channelId = channelId;
	}

	public String getOriginalChannelId() {
		return GetterUtil.getString(_originalChannelId);
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public int getPermissionType() {
		return _permissionType;
	}

	@Override
	public void setPermissionType(int permissionType) {
		_permissionType = permissionType;
	}

	@Override
	public long getWorkspaceGroupId() {
		return _workspaceGroupId;
	}

	@Override
	public void setWorkspaceGroupId(long workspaceGroupId) {
		_columnBitmask |= WORKSPACEGROUPID_COLUMN_BITMASK;

		if (!_setOriginalWorkspaceGroupId) {
			_setOriginalWorkspaceGroupId = true;

			_originalWorkspaceGroupId = _workspaceGroupId;
		}

		_workspaceGroupId = workspaceGroupId;
	}

	public long getOriginalWorkspaceGroupId() {
		return _originalWorkspaceGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FaroChannel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FaroChannel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FaroChannel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FaroChannelImpl faroChannelImpl = new FaroChannelImpl();

		faroChannelImpl.setFaroChannelId(getFaroChannelId());
		faroChannelImpl.setGroupId(getGroupId());
		faroChannelImpl.setUserId(getUserId());
		faroChannelImpl.setUserName(getUserName());
		faroChannelImpl.setCreateTime(getCreateTime());
		faroChannelImpl.setModifiedTime(getModifiedTime());
		faroChannelImpl.setChannelId(getChannelId());
		faroChannelImpl.setName(getName());
		faroChannelImpl.setPermissionType(getPermissionType());
		faroChannelImpl.setWorkspaceGroupId(getWorkspaceGroupId());

		faroChannelImpl.resetOriginalValues();

		return faroChannelImpl;
	}

	@Override
	public int compareTo(FaroChannel faroChannel) {
		long primaryKey = faroChannel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FaroChannel)) {
			return false;
		}

		FaroChannel faroChannel = (FaroChannel)object;

		long primaryKey = faroChannel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalUserId = _userId;

		_setOriginalUserId = false;

		_originalChannelId = _channelId;

		_originalWorkspaceGroupId = _workspaceGroupId;

		_setOriginalWorkspaceGroupId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FaroChannel> toCacheModel() {
		FaroChannelCacheModel faroChannelCacheModel =
			new FaroChannelCacheModel();

		faroChannelCacheModel.faroChannelId = getFaroChannelId();

		faroChannelCacheModel.groupId = getGroupId();

		faroChannelCacheModel.userId = getUserId();

		faroChannelCacheModel.userName = getUserName();

		String userName = faroChannelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			faroChannelCacheModel.userName = null;
		}

		faroChannelCacheModel.createTime = getCreateTime();

		faroChannelCacheModel.modifiedTime = getModifiedTime();

		faroChannelCacheModel.channelId = getChannelId();

		String channelId = faroChannelCacheModel.channelId;

		if ((channelId != null) && (channelId.length() == 0)) {
			faroChannelCacheModel.channelId = null;
		}

		faroChannelCacheModel.name = getName();

		String name = faroChannelCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			faroChannelCacheModel.name = null;
		}

		faroChannelCacheModel.permissionType = getPermissionType();

		faroChannelCacheModel.workspaceGroupId = getWorkspaceGroupId();

		return faroChannelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FaroChannel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FaroChannel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroChannel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FaroChannel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FaroChannel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FaroChannel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroChannel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FaroChannel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FaroChannel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _faroChannelId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private long _createTime;
	private long _modifiedTime;
	private String _channelId;
	private String _originalChannelId;
	private String _name;
	private int _permissionType;
	private long _workspaceGroupId;
	private long _originalWorkspaceGroupId;
	private boolean _setOriginalWorkspaceGroupId;
	private long _columnBitmask;
	private FaroChannel _escapedModel;

}