/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.contacts.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.faro.contacts.model.ContactsCardTemplate;
import com.liferay.osb.faro.contacts.model.ContactsCardTemplateModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ContactsCardTemplate service. Represents a row in the &quot;OSBFaro_ContactsCardTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContactsCardTemplateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactsCardTemplateImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see ContactsCardTemplateImpl
 * @generated
 */
public class ContactsCardTemplateModelImpl
	extends BaseModelImpl<ContactsCardTemplate>
	implements ContactsCardTemplateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contacts card template model instance should use the <code>ContactsCardTemplate</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBFaro_ContactsCardTemplate";

	public static final Object[][] TABLE_COLUMNS = {
		{"contactsCardTemplateId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createTime", Types.BIGINT}, {"modifiedTime", Types.BIGINT},
		{"name", Types.VARCHAR}, {"settings_", Types.VARCHAR},
		{"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("contactsCardTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("settings_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBFaro_ContactsCardTemplate (contactsCardTemplateId LONG not null primary key,groupId LONG,userId LONG,userName VARCHAR(75) null,createTime LONG,modifiedTime LONG,name VARCHAR(75) null,settings_ STRING null,type_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBFaro_ContactsCardTemplate";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contactsCardTemplate.contactsCardTemplateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBFaro_ContactsCardTemplate.contactsCardTemplateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.contacts.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.faro.contacts.model.ContactsCardTemplate"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.contacts.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.faro.contacts.model.ContactsCardTemplate"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.contacts.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.faro.contacts.model.ContactsCardTemplate"),
		true);

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long CONTACTSCARDTEMPLATEID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.faro.contacts.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.faro.contacts.model.ContactsCardTemplate"));

	public ContactsCardTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContactsCardTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContactsCardTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return ContactsCardTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContactsCardTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactsCardTemplate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContactsCardTemplate)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContactsCardTemplate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContactsCardTemplate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContactsCardTemplate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContactsCardTemplate, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContactsCardTemplate, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ContactsCardTemplate>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ContactsCardTemplate.class.getClassLoader(),
			ContactsCardTemplate.class, ModelWrapper.class);

		try {
			Constructor<ContactsCardTemplate> constructor =
				(Constructor<ContactsCardTemplate>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ContactsCardTemplate, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ContactsCardTemplate, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ContactsCardTemplate, Object>>();
		Map<String, BiConsumer<ContactsCardTemplate, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ContactsCardTemplate, ?>>();

		attributeGetterFunctions.put(
			"contactsCardTemplateId",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getContactsCardTemplateId();
				}

			});
		attributeSetterBiConsumers.put(
			"contactsCardTemplateId",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object contactsCardTemplateIdObject) {

					contactsCardTemplate.setContactsCardTemplateId(
						(Long)contactsCardTemplateIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object groupIdObject) {

					contactsCardTemplate.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object userIdObject) {

					contactsCardTemplate.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object userNameObject) {

					contactsCardTemplate.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createTime",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getCreateTime();
				}

			});
		attributeSetterBiConsumers.put(
			"createTime",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object createTimeObject) {

					contactsCardTemplate.setCreateTime((Long)createTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedTime",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getModifiedTime();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedTime",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object modifiedTimeObject) {

					contactsCardTemplate.setModifiedTime(
						(Long)modifiedTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object nameObject) {

					contactsCardTemplate.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"settings",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getSettings();
				}

			});
		attributeSetterBiConsumers.put(
			"settings",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object settingsObject) {

					contactsCardTemplate.setSettings((String)settingsObject);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<ContactsCardTemplate, Object>() {

				@Override
				public Object apply(ContactsCardTemplate contactsCardTemplate) {
					return contactsCardTemplate.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<ContactsCardTemplate, Object>() {

				@Override
				public void accept(
					ContactsCardTemplate contactsCardTemplate,
					Object typeObject) {

					contactsCardTemplate.setType((Integer)typeObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getContactsCardTemplateId() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setContactsCardTemplateId(long contactsCardTemplateId) {
		_contactsCardTemplateId = contactsCardTemplateId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_createTime = createTime;
	}

	@Override
	public long getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(long modifiedTime) {
		_modifiedTime = modifiedTime;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getSettings() {
		if (_settings == null) {
			return "";
		}
		else {
			return _settings;
		}
	}

	@Override
	public void setSettings(String settings) {
		_settings = settings;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ContactsCardTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContactsCardTemplate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContactsCardTemplate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContactsCardTemplateImpl contactsCardTemplateImpl =
			new ContactsCardTemplateImpl();

		contactsCardTemplateImpl.setContactsCardTemplateId(
			getContactsCardTemplateId());
		contactsCardTemplateImpl.setGroupId(getGroupId());
		contactsCardTemplateImpl.setUserId(getUserId());
		contactsCardTemplateImpl.setUserName(getUserName());
		contactsCardTemplateImpl.setCreateTime(getCreateTime());
		contactsCardTemplateImpl.setModifiedTime(getModifiedTime());
		contactsCardTemplateImpl.setName(getName());
		contactsCardTemplateImpl.setSettings(getSettings());
		contactsCardTemplateImpl.setType(getType());

		contactsCardTemplateImpl.resetOriginalValues();

		return contactsCardTemplateImpl;
	}

	@Override
	public int compareTo(ContactsCardTemplate contactsCardTemplate) {
		long primaryKey = contactsCardTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ContactsCardTemplate)) {
			return false;
		}

		ContactsCardTemplate contactsCardTemplate =
			(ContactsCardTemplate)object;

		long primaryKey = contactsCardTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactsCardTemplate> toCacheModel() {
		ContactsCardTemplateCacheModel contactsCardTemplateCacheModel =
			new ContactsCardTemplateCacheModel();

		contactsCardTemplateCacheModel.contactsCardTemplateId =
			getContactsCardTemplateId();

		contactsCardTemplateCacheModel.groupId = getGroupId();

		contactsCardTemplateCacheModel.userId = getUserId();

		contactsCardTemplateCacheModel.userName = getUserName();

		String userName = contactsCardTemplateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contactsCardTemplateCacheModel.userName = null;
		}

		contactsCardTemplateCacheModel.createTime = getCreateTime();

		contactsCardTemplateCacheModel.modifiedTime = getModifiedTime();

		contactsCardTemplateCacheModel.name = getName();

		String name = contactsCardTemplateCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			contactsCardTemplateCacheModel.name = null;
		}

		contactsCardTemplateCacheModel.settings = getSettings();

		String settings = contactsCardTemplateCacheModel.settings;

		if ((settings != null) && (settings.length() == 0)) {
			contactsCardTemplateCacheModel.settings = null;
		}

		contactsCardTemplateCacheModel.type = getType();

		return contactsCardTemplateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContactsCardTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactsCardTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ContactsCardTemplate)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ContactsCardTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactsCardTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((ContactsCardTemplate)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContactsCardTemplate>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _contactsCardTemplateId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userName;
	private long _createTime;
	private long _modifiedTime;
	private String _name;
	private String _settings;
	private int _type;
	private long _columnBitmask;
	private ContactsCardTemplate _escapedModel;

}